import type { JogoCatalogo } from './tipos.js';

export const CATALOGO_JOGOS: JogoCatalogo[] = [
  {
    id: 'martelo-thor',
    nome: 'Martelo do Thor',
    descricao: 'Versão nativa reescrita para a plataforma atual, com fluxo leve, responsivo e muito mais estável.',
    categoria: 'Força máxima',
    origem: 'nativo',
    modoExecucao: 'embutido',
    requerConexao: true,
    etiquetas: ['ranking', 'nativo', 'reescrito'],
    destaque: true,
  },
  {
    id: 'soco-do-seculo',
    nome: 'Soco do Século',
    descricao: 'Classifica a força aplicada e transforma a célula de carga em um medidor de impacto.',
    categoria: 'Força máxima',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/01-soco-do-seculo.html',
    requerConexao: true,
    etiquetas: ['template', 'educacional'],
  },
  {
    id: 'beat-smasher',
    nome: 'Beat Smasher',
    descricao: 'Jogo de ritmo em que a pressão precisa acontecer no tempo certo usando a força como entrada.',
    categoria: 'Ritmo',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/02-beat-smasher.html',
    requerConexao: true,
    etiquetas: ['template', 'ritmo'],
  },
  {
    id: 'precisao-extrema',
    nome: 'Precisão Extrema',
    descricao: 'Treina controle fino para atingir alvos de força específicos sem passar do ponto.',
    categoria: 'Precisão',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/03-precisao-extrema.html',
    requerConexao: true,
    etiquetas: ['template', 'controle fino'],
  },
  {
    id: 'escalada-jaragua',
    nome: 'Escalada do Jaraguá',
    descricao: 'Simula uma escalada em que o jogador precisa administrar força e fôlego em etapas.',
    categoria: 'Resistência',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/04-escalada-jaragua.html',
    requerConexao: true,
    etiquetas: ['template', 'resistência'],
  },
  {
    id: 'reflexo-relampago',
    nome: 'Reflexo Relâmpago',
    descricao: 'Jogo de resposta rápida onde a força deve entrar no instante certo após o estímulo.',
    categoria: 'Reflexo',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/05-reflexo-relampago.html',
    requerConexao: true,
    etiquetas: ['template', 'tempo de reação'],
  },
  {
    id: 'treino-rocky',
    nome: 'Treino do Rocky',
    descricao: 'Sessões progressivas de esforço para repetição e condicionamento usando a célula como entrada.',
    categoria: 'Treino',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/06-treino-rocky.html',
    requerConexao: true,
    etiquetas: ['template', 'séries'],
  },
  {
    id: 'roleta-da-forca',
    nome: 'Roleta da Força',
    descricao: 'Formato de sorte e premiação em que a intensidade aplicada determina o resultado.',
    categoria: 'Casual',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/07-roleta-forca.html',
    requerConexao: true,
    etiquetas: ['template', 'casual'],
  },
  {
    id: 'reacao-em-cadeia',
    nome: 'Reação em Cadeia',
    descricao: 'Sequência de alvos que exige controle rápido de força em múltiplas etapas consecutivas.',
    categoria: 'Coordenação',
    origem: 'legado-v1',
    modoExecucao: 'popup',
    arquivoPublico: 'legado/jogos/08-reacao-cadeia.html',
    requerConexao: true,
    etiquetas: ['template', 'cadeia de alvos'],
  },
];

export function obterJogoPorId(id: string): JogoCatalogo | undefined {
  return CATALOGO_JOGOS.find(jogo => jogo.id === id);
}
